require(data.table)
require(googleVis)
require(shiny)
require(plotrix)
require(caret)
require(gbm)
require(verification)
load("data.RData")
gbmVar = c("day","state","disabled", "years_membership", "risk_factor", "married")